name: PrimateBuilding
version: '${project.version}'
main: ru.samsonium.primate.building.PrimateBuilding
api-version: '1.20'
commands:
  repair:
    description: Починить предмет
    usage: /<command>
  tools:
    description: Получить хорошие инструменты
    usage: /<command>
  fight:
    description: Получить зачарованную броню и оружие
    usage: /<command>
  fly:
    description: Переключить режим полёта
    usage: /<command>
  god:
    description: Переключить режим бога
    usage: /<command>
